language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9
  - openjdk10
#  - openjdk11 Disabled because jacoco can't instrument correctly

after_success:
  - mvn clean test jacoco:report coveralls:report